import React from "react";
import Link from "next/link";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { createPageMetadata } from "@/lib/seo";
import "./project.css";

export const metadata = createPageMetadata({
  title: "Projects",
  description:
    "Explore projects by Shashi Preetham Awari, also known as Shashi Awari, including full-stack apps, AI work, APIs, machine learning ideas, and interactive web experiences.",
  path: "/projects",
  keywords: ["Shashi Awari projects", "Shashi Preetham Awari portfolio projects"],
});

// Edit this list to add, remove, or reorder projects.
const projects = [
  {
    title: "FindH",
    mediaSrc: "findh.png",
    technologies: "Next.js, Node.js, Supabase, PostgreSQL, GSAP",
    description:
      "FindH is a rental verification platform that connects tenants with nearby agents who can physically verify properties. Users can book agents to inspect listings, upload verification documents, and receive admin-approved reports privately. The system includes agent dashboards, admin verification panels, document management, and secure booking workflows.",
    href: "https://frontend-nine-ashen-8v3tcyasob.vercel.app/",
  },
  {
    title: "Defungi CNN",
    mediaSrc: "fungi.png",
    technologies: "Python, TensorFlow, CNN, Deep Learning",
    description:
      "Defungi CNN is a deep learning project that uses Convolutional Neural Networks to classify fungal images for medical analysis. The model processes image datasets and predicts fungal types with high accuracy, demonstrating practical computer vision and healthcare AI applications.",
    href: "https://github.com/Shashiawari/Defungi-CNN",
  },
  {
    title: "Detect GPT",
    mediaSrc: "gpt.png",
    technologies: "Python, NLP, Machine Learning",
    description:
      "Detect GPT is an AI tool designed to detect whether text is generated by large language models. The system analyzes linguistic patterns and probability distributions to distinguish between human-written and AI-generated content.",
    href: "https://github.com/Shashiawari",
  },
  {
    title: "GenAI",
    mediaSrc: "gen.mp4",
    technologies: "Next.js, HTML, CSS, JavaScript, AI API",
    description:
      "GenAI is a generative AI platform that allows users to create dynamic content such as text and images using modern AI APIs. It provides an intuitive interface for developers and creators to experiment with AI-powered workflows.",
    href: "https://main--genn-ai.netlify.app/",
  },
  {
    title: "Chit-Chat",
    mediaSrc: "chit.mp4",
    technologies: "Node.js, HTML, CSS, JavaScript, Socket.io",
    description:
      "Chit Chat is a real-time messaging application built using Node.js, Express, and Socket.io. It supports private chat rooms generated with UUID for secure conversations and enables instant messaging and file sharing in a simple and responsive interface.",
    href: "https://chit-chat-5e9g.onrender.com/",
  },
  {
    title: "JapEase",
    mediaSrc: "Jap.mp4",
    technologies: "React.js, Node.js, HTML, CSS, JavaScript, API",
    description:
      "JapEase is a job discovery application built with React.js that helps students find real-time job opportunities. It focuses on API integrations, dynamic UI updates, and responsive design to provide a smooth job search experience.",
    href: "https://japease2.onrender.com/",
  },
  {
    title: "SnapGen",
    mediaSrc: "snapg.mp4",
    technologies: "Node.js, HTML, CSS, JavaScript, Unsplash API",
    description:
      "SnapGen is an image generation and discovery web application powered by the Unsplash API. It allows users to search, preview, and download high-quality images with a fast and minimal interface.",
    href: "https://snapgen.onrender.com/",
  },
  {
    title: "NexGen",
    mediaSrc: "nex.mp4",
    technologies: "Next.js",
    description:
      "NexGen is an innovative platform where users can create custom websites with the assistance of a dedicated personal developer. The project leverages Next.js to deliver a smooth and efficient user experience, empowering individuals to bring their digital visions to life effortlessly.",
    href: "https://nexxgenn.netlify.app/",
  },
  {
    title: "Next Level Food",
    mediaSrc: "food.mp4",
    technologies: "React, SQLite",
    description:
      "Next Level Food is a recipe-sharing platform where users can explore and contribute food recipes. The application focuses on an intuitive UI, allowing users to browse dishes, view cooking instructions, and share their own culinary creations.",
    href: "https://nextlevelfoods.onrender.com/",
  },
  {
    title: "Micro Course Converter",
    mediaSrc: "taads.png",
    technologies: "Python, NLP, AI",
    description:
      "Micro Course Converter is an AI-powered tool that converts long educational content into structured micro-learning modules. It uses natural language processing to summarize and restructure information into concise learning segments.",
    href: "https://github.com/Shashiawari",
  },
];

const ArrowIcon = ({ className }) => (
  <svg
    viewBox="0 0 24 24"
    className={className}
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
  >
    <path d="M16.1716 10.9999L10.8076 5.63589L12.2218 4.22168L20 11.9999L12.2218 19.778L10.8076 18.3638L16.1716 12.9999H4V10.9999H16.1716Z"></path>
  </svg>
);

const ProjectCard = ({ project, index }) => {
  const number = String(index + 1).padStart(2, "0");
  const mediaSrc = project.mediaSrc ?? project.videoSrc ?? project.imageSrc;
  const isImage = /\.(png|jpe?g|webp|gif|avif|svg)$/i.test(mediaSrc || "");

  return (
    <article className="projectCard" style={{ "--card-index": index }}>
      <div className="projectCardMedia">
        <span className="projectCardNumber">{number}</span>
        {isImage ? (
          <img src={mediaSrc} alt={project.title} loading="lazy" decoding="async" />
        ) : (
          <video
            src={mediaSrc}
            muted
            autoPlay
            loop
            playsInline
            preload="metadata"
            aria-label={project.title}
          ></video>
        )}
      </div>

      <div className="projectCardBody">
        <p className="projectCardKicker">Featured Project</p>
        <h3>{project.title}</h3>
        <p className="projectCardTech">Technologies Used: {project.technologies}</p>
        <p className="projectCardDescription">{project.description}</p>

        <Link href={project.href} className="animated-button projectCardButton">
          <ArrowIcon className="arr-2" />
          <span className="text">Link</span>
          <span className="circle"></span>
          <ArrowIcon className="arr-1" />
        </Link>
      </div>
    </article>
  );
};

const ProjectsPage = () => {
  return (
    <div className="proj projectPage">
      <Navbar />

      <section className="projectGridSection">
        <div className="container projectGridContainer">
          <div className="projectGridIntro">
            <div>
              <p className="projectGridEyebrow">Selected Work</p>
              <h1>Projects</h1>
              <p className="projectGridLead">
               Make sure to view and visit them.
              </p>
            </div>

            <div className="projectGridStat">
              <span>{String(projects.length).padStart(2, "0")}</span>
              <p>Projects and counting</p>
            </div>
          </div>

          <div className="projectCardsGrid">
            {projects.map((project, index) => (
              <ProjectCard key={project.title} project={project} index={index} />
            ))}
          </div>
        </div>
      </section>

      <section className="projectMore text-center">
        <h4>And many more, visit my GitHub profile</h4>
        <Link
          className="projectGithubLink"
          href={"https://github.com/Shashiawari"}
          aria-label="Visit GitHub profile"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="36"
            height="36"
            fill="white"
            className="bi bi-github"
            viewBox="0 0 16 16"
          >
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8" />
          </svg>
        </Link>
      </section>

      <Footer />
    </div>
  );
};

export default ProjectsPage;
