import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from "@/components/BootstrapClient";
import CustomCursor from "@/components/customcursor/Cutomcursor";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shashi Awari",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body style={{background:"black"}}>
      <CustomCursor/>
      {children}<BootstrapClient/></body>
    </html>
  );
}
